export const routes = {
  home: "/",
  authLogin: "/auth/login",
  authRegister: "/auth/register",
  authRole: "/auth/role",
  dashboard: "/dashboard",
  dashboardHousehold: "/dashboard/household",
  dashboardCollector: "/dashboard/collector",
  dashboardIndustry: "/dashboard/industry",
  marketplace: "/marketplace",
  marketplaceWaste: "/marketplace/waste",
  marketplaceMaterials: "/marketplace/materials",
  listingsNew: "/listings/new",
  listingDetail: (id: string) => `/listings/${id}`,
  listingEdit: (id: string) => `/listings/${id}/edit`,
  wasteCategories: "/master/waste-categories",
  pickupRoutes: "/pickup/routes",
  pickupDetail: (id: string) => `/pickup/${id}`,
  pickupOptimizer: "/pickup/optimizer",
  classificationDemo: "/classification/demo",
  collectorPickups: "/collector/pickups",
  collectorSorting: "/collector/sorting",
  collectorMaterialsNew: "/collector/materials/new",
  orders: "/orders",
  ordersNew: "/orders/new",
  checkout: "/checkout",
  negotiations: "/negotiations",
  negotiationDetail: (id: string) => `/negotiations/${id}`,
  negotiationChat: (id: string) => `/negotiations/${id}/chat`,
  transactionDetail: (id: string) => `/transactions/${id}`,
  transactions: "/transactions",
  materialDetail: (id: string) => `/materials/${id}`,
  traceability: (materialId: string) => `/traceability/${materialId}`,
  reviews: "/reviews",
  reviewsNew: "/reviews/new",
  impact: "/impact",
  reports: "/reports",
  deployReadiness: "/deploy-readiness",
  profile: "/profile",
  myMaterials: "/my-materials",
  pickupConfirm: "/pickup/confirm",
  notifications: "/notifications",
  messages: "/messages",
  pickupTracking: "/pickup/tracking",
  demo: "/demo",
  points: "/points",
  collectorHandledCategories: "/collector/handled-categories",
} as const;
